name: style

on: [push, pull_request]

jobs:
    tox:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python_version:
            - "3.8"
          tox_env:
            - style
          include:
            - tox_env: style
              friendly_name: Style
        fail-fast: false
      name: ${{ matrix.friendly_name }}
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ env.ref }}
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python_version }}
        - name: Install tox
          run: |
            python -m pip install --upgrade pip
            pip install tox
        - name: Tox test
          env:
            TOXENV: ${{ matrix.tox_env }}
          run: tox
